name: Commit Check

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  commit-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Commit Messages
        run: |
          # Simplified Regex pattern to enforce Conventional Commits
          pattern='^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([\w\.\-]+\))?: .+'

          # Fetch the commit message
          commit_message=$(git log -1 --pretty=%B)

          # Strip surrounding quotes (if any) from the commit message
          commit_message=$(echo "$commit_message" | sed -e 's/^"//' -e 's/"$//')

          echo "Validating commit message: \"$commit_message\""

          # Validate the commit message
          if ! echo "$commit_message" | grep -P "$pattern"; then
            echo "Invalid commit message: \"$commit_message\""
            echo "Commit messages must follow Conventional Commits format."
            echo "See https://www.conventionalcommits.org/ for more details."
            exit 1
          fi

      - name: Run Commit Message Check
        uses: commit-check/commit-check-action@v1
        with:
          message: true
          branch: true
          author-name: true
          author-email: true
          commit-signoff: true
          dry-run: false
          job-summary: true
